"use server";

import { redirect } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { assertToolAccess } from "@/lib/auth/authz";
import { failIfError, failWith } from "@/lib/editorial/action-result";
import {
  generateRelatedQuestion,
  runDiscussTurn,
  type ChatTurnMessage,
  type QuestionContext,
} from "@/lib/editorial-inquiry/ai";
import {
  getInquiryDetail,
  getQuestionChat,
  type ChatMessageRecord,
} from "@/lib/editorial-inquiry/queries";
import {
  activeChildren,
  ancestryPath,
  inheritedContextNotes,
  type ContextNoteKind,
  type ContextNoteRecord,
  type QuestionRecord,
} from "@/lib/editorial-inquiry/tree";

const TOOL_KEY = "editorial-inquiry";
const LIST_PATH = "/editorial-inquiry";

type ActionResult<T> = { ok: true; data: T } | { ok: false; error: string };

function ok<T>(data: T): ActionResult<T> {
  return { ok: true, data };
}

function err<T>(error: unknown): ActionResult<T> {
  const message = error instanceof Error ? error.message : "Something went wrong.";
  console.error("Editorial Inquiry action failed:", error);
  return { ok: false, error: message };
}

/** Real HTML form, redirect-based like the rest of the portal — see design doc §3. */
export async function startNewInquiry(formData: FormData): Promise<void> {
  await assertToolAccess(TOOL_KEY);
  const seedQuestion = String(formData.get("seed_question") ?? "").trim();
  if (!seedQuestion) failWith(LIST_PATH, "A guiding question is required to start an inquiry.");

  const supabase = await createClient();
  const { data, error } = await supabase.rpc("ei_create_inquiry", {
    p_seed_question: seedQuestion,
  });
  failIfError(error, LIST_PATH, "Could not start that inquiry");

  redirect(`${LIST_PATH}?inquiry=${data!.id}`);
}

async function loadQuestionAndContext(
  questionId: string,
  kind: "sibling" | "child" | "discuss",
): Promise<{ inquiryId: string; question: QuestionRecord; context: QuestionContext }> {
  const supabase = await createClient();
  const { data: questionRow, error } = await supabase
    .from("ei_questions")
    .select("*")
    .eq("id", questionId)
    .single();
  if (error || !questionRow) throw new Error("Could not find that question.");

  const detail = await getInquiryDetail(questionRow.inquiry_id);
  if (!detail) throw new Error("Could not find that question's inquiry.");
  const question = detail.questions.find((q) => q.id === questionId);
  if (!question) throw new Error("Could not find that question.");

  const ancestry = ancestryPath(detail.questions, questionId)
    .slice()
    .reverse()
    .map((id) => {
      const q = detail.questions.find((candidate) => candidate.id === id)!;
      return { depth: q.depth, text: q.text };
    });

  const relatedParentId = kind === "child" ? question.id : question.parentId;
  const existingRelated = relatedParentId
    ? activeChildren(detail.questions, relatedParentId)
        .filter((q) => q.id !== question.id)
        .map((q) => q.text)
    : [];

  const inheritedContext = inheritedContextNotes(
    detail.questions,
    detail.contextNotes,
    questionId,
  ).map((r) => ({ kind: r.note.kind, body: r.note.body }));

  return {
    inquiryId: questionRow.inquiry_id,
    question,
    context: {
      seedQuestion: detail.inquiry.seedQuestion,
      ancestry,
      existingRelated,
      inheritedContext,
    },
  };
}

async function insertQuestion(params: {
  inquiryId: string;
  parentId: string;
  depth: number;
  text: string;
  hasAssumption: boolean;
  assumptionText: string | null;
  createdBy: string;
}): Promise<QuestionRecord> {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("ei_questions")
    .insert({
      inquiry_id: params.inquiryId,
      parent_id: params.parentId,
      depth: params.depth,
      text: params.text,
      has_assumption: params.hasAssumption,
      assumption_text: params.assumptionText,
      created_by: params.createdBy,
    })
    .select("*")
    .single();
  if (error || !data) throw new Error(error?.message ?? "Could not add that question.");
  return {
    id: data.id,
    inquiryId: data.inquiry_id,
    parentId: data.parent_id,
    depth: data.depth,
    text: data.text,
    status: data.status as QuestionRecord["status"],
    hasAssumption: data.has_assumption,
    assumptionText: data.assumption_text,
    reframedFromText: data.reframed_from_text,
    manualDx: data.manual_dx,
    manualDy: data.manual_dy,
    createdBy: data.created_by,
    createdAt: data.created_at,
    updatedAt: data.updated_at,
  };
}

/** Explore: a new sibling angle, generated by the model. */
export async function exploreQuestion(questionId: string): Promise<ActionResult<QuestionRecord>> {
  try {
    const { profile } = await assertToolAccess(TOOL_KEY);
    const { inquiryId, question, context } = await loadQuestionAndContext(questionId, "sibling");
    if (question.depth < 1 || !question.parentId) {
      throw new Error("The guiding question has no sibling to explore.");
    }
    const generated = await generateRelatedQuestion("sibling", context);
    const created = await insertQuestion({
      inquiryId,
      parentId: question.parentId,
      depth: question.depth,
      text: generated.text,
      hasAssumption: generated.hasAssumption,
      assumptionText: generated.assumptionText,
      createdBy: profile.id,
    });
    return ok(created);
  } catch (error) {
    return err(error);
  }
}

/** Drill down: a new, narrower child, generated by the model. */
export async function drillDownQuestion(questionId: string): Promise<ActionResult<QuestionRecord>> {
  try {
    const { profile } = await assertToolAccess(TOOL_KEY);
    const { inquiryId, question, context } = await loadQuestionAndContext(questionId, "child");
    const generated = await generateRelatedQuestion("child", context);
    const created = await insertQuestion({
      inquiryId,
      parentId: question.id,
      depth: question.depth + 1,
      text: generated.text,
      hasAssumption: generated.hasAssumption,
      assumptionText: generated.assumptionText,
      createdBy: profile.id,
    });
    return ok(created);
  } catch (error) {
    return err(error);
  }
}

/**
 * The manual fallback when the model is unavailable or a reporter just
 * wants to type their own angle — see design doc §8. Bypasses ai.ts
 * entirely; the reporter's own text becomes the new sibling/child.
 */
export async function addQuestionManually(
  questionId: string,
  kind: "sibling" | "child",
  text: string,
): Promise<ActionResult<QuestionRecord>> {
  try {
    const { profile } = await assertToolAccess(TOOL_KEY);
    const trimmed = text.trim();
    if (!trimmed) throw new Error("A question is required.");

    const supabase = await createClient();
    const { data: questionRow, error } = await supabase
      .from("ei_questions")
      .select("*")
      .eq("id", questionId)
      .single();
    if (error || !questionRow) throw new Error("Could not find that question.");

    if (kind === "sibling") {
      if (!questionRow.parent_id) throw new Error("The guiding question has no sibling to add.");
      const created = await insertQuestion({
        inquiryId: questionRow.inquiry_id,
        parentId: questionRow.parent_id,
        depth: questionRow.depth,
        text: trimmed,
        hasAssumption: false,
        assumptionText: null,
        createdBy: profile.id,
      });
      return ok(created);
    }

    const created = await insertQuestion({
      inquiryId: questionRow.inquiry_id,
      parentId: questionRow.id,
      depth: questionRow.depth + 1,
      text: trimmed,
      hasAssumption: false,
      assumptionText: null,
      createdBy: profile.id,
    });
    return ok(created);
  } catch (error) {
    return err(error);
  }
}

export async function rejectQuestion(questionId: string): Promise<ActionResult<null>> {
  try {
    await assertToolAccess(TOOL_KEY);
    const supabase = await createClient();
    const { error } = await supabase
      .from("ei_questions")
      .update({ status: "rejected" })
      .eq("id", questionId)
      .eq("status", "active");
    if (error) throw new Error(error.message);
    return ok(null);
  } catch (error) {
    return err(error);
  }
}

export async function promoteQuestion(questionId: string): Promise<ActionResult<null>> {
  try {
    await assertToolAccess(TOOL_KEY);
    const supabase = await createClient();
    const { error } = await supabase
      .from("ei_questions")
      .update({ status: "promoted" })
      .eq("id", questionId)
      .eq("status", "active");
    if (error) throw new Error(error.message);
    return ok(null);
  } catch (error) {
    return err(error);
  }
}

/** Persists a reporter's canvas drag as an offset from the computed layout position. */
export async function moveQuestion(
  questionId: string,
  manualDx: number,
  manualDy: number,
): Promise<ActionResult<null>> {
  try {
    await assertToolAccess(TOOL_KEY);
    const supabase = await createClient();
    const { error } = await supabase
      .from("ei_questions")
      .update({ manual_dx: manualDx, manual_dy: manualDy })
      .eq("id", questionId);
    if (error) throw new Error(error.message);
    return ok(null);
  } catch (error) {
    return err(error);
  }
}

export async function addContextNote(
  questionId: string,
  kind: ContextNoteKind,
  body: string,
): Promise<ActionResult<ContextNoteRecord>> {
  try {
    const { profile } = await assertToolAccess(TOOL_KEY);
    const trimmed = body.trim();
    if (!trimmed) throw new Error("A note, link, or excerpt is required.");

    const supabase = await createClient();
    const { data, error } = await supabase
      .from("ei_context_notes")
      .insert({ question_id: questionId, kind, body: trimmed, created_by: profile.id })
      .select("*")
      .single();
    if (error || !data) throw new Error(error?.message ?? "Could not add that context.");
    return ok({
      id: data.id,
      questionId: data.question_id,
      kind: data.kind as ContextNoteKind,
      body: data.body,
      createdBy: data.created_by,
      createdAt: data.created_at,
    });
  } catch (error) {
    return err(error);
  }
}

/** Loaded lazily when the inspector's Discuss panel opens for a question. */
export async function loadDiscussThread(
  questionId: string,
): Promise<ActionResult<ChatMessageRecord[]>> {
  try {
    await assertToolAccess(TOOL_KEY);
    return ok(await getQuestionChat(questionId));
  } catch (error) {
    return err(error);
  }
}

function toChatMessageRecord(row: {
  id: string;
  question_id: string;
  role: string;
  body: string;
  action_kind: string | null;
  action_payload: unknown;
  applied_at: string | null;
  created_by: string | null;
  created_at: string;
}): ChatMessageRecord {
  return {
    id: row.id,
    questionId: row.question_id,
    role: row.role as "user" | "assistant",
    body: row.body,
    actionKind: row.action_kind as ChatMessageRecord["actionKind"],
    actionPayload: row.action_payload as Record<string, unknown> | null,
    appliedAt: row.applied_at,
    createdBy: row.created_by,
    createdAt: row.created_at,
  };
}

export interface DiscussTurnResult {
  userMessage: ChatMessageRecord;
  assistantMessage: ChatMessageRecord;
  /** Set when the model spun off a sibling immediately, per design doc §4. */
  createdQuestion: QuestionRecord | null;
  /** Set when the model attached a context note immediately. */
  createdContextNote: ContextNoteRecord | null;
}

/** One turn of a question's discuss thread — see design doc §2/§4 for what each action kind does. */
export async function sendDiscussMessage(
  questionId: string,
  message: string,
): Promise<ActionResult<DiscussTurnResult>> {
  try {
    const { profile } = await assertToolAccess(TOOL_KEY);
    const trimmed = message.trim();
    if (!trimmed) throw new Error("A message is required.");

    const { inquiryId, question, context } = await loadQuestionAndContext(questionId, "discuss");
    const supabase = await createClient();

    const priorRows = (
      await supabase
        .from("ei_chat_messages")
        .select("*")
        .eq("question_id", questionId)
        .order("created_at")
    ).data;
    const priorMessages: ChatTurnMessage[] = (priorRows ?? []).map((row) => ({
      role: row.role as "user" | "assistant",
      body: row.body,
    }));

    const { data: userRow, error: userError } = await supabase
      .from("ei_chat_messages")
      .insert({ question_id: questionId, role: "user", body: trimmed, created_by: profile.id })
      .select("*")
      .single();
    if (userError || !userRow)
      throw new Error(userError?.message ?? "Could not send that message.");

    const result = await runDiscussTurn(
      {
        text: question.text,
        hasAssumption: question.hasAssumption,
        assumptionText: question.assumptionText,
      },
      context,
      priorMessages,
      trimmed,
    );

    let createdQuestion: QuestionRecord | null = null;
    let createdContextNote: ContextNoteRecord | null = null;
    let actionPayload: Record<string, unknown> | null = null;
    let appliedAt: string | null = null;

    if (result.action?.kind === "sibling") {
      if (!question.parentId) {
        // The root has no sibling to spin off — treat as a plain reply.
      } else {
        createdQuestion = await insertQuestion({
          inquiryId,
          parentId: question.parentId,
          depth: question.depth,
          text: result.action.text,
          hasAssumption: false,
          assumptionText: null,
          createdBy: profile.id,
        });
        actionPayload = { questionId: createdQuestion.id };
        appliedAt = new Date().toISOString();
      }
    } else if (result.action?.kind === "context") {
      const { data: noteRow, error: noteError } = await supabase
        .from("ei_context_notes")
        .insert({
          question_id: questionId,
          kind: "note",
          body: result.action.text,
          created_by: profile.id,
        })
        .select("*")
        .single();
      if (noteError || !noteRow)
        throw new Error(noteError?.message ?? "Could not attach that context.");
      createdContextNote = {
        id: noteRow.id,
        questionId: noteRow.question_id,
        kind: noteRow.kind as ContextNoteKind,
        body: noteRow.body,
        createdBy: noteRow.created_by,
        createdAt: noteRow.created_at,
      };
      actionPayload = { contextNoteId: createdContextNote.id };
      appliedAt = new Date().toISOString();
    } else if (result.action?.kind === "reframe") {
      actionPayload = { text: result.action.text };
      // appliedAt stays null — the reporter applies a reframe explicitly.
    }

    const { data: assistantRow, error: assistantError } = await supabase
      .from("ei_chat_messages")
      .insert({
        question_id: questionId,
        role: "assistant",
        body: result.reply,
        action_kind: result.action?.kind ?? null,
        action_payload: actionPayload,
        applied_at: appliedAt,
      })
      .select("*")
      .single();
    if (assistantError || !assistantRow) {
      throw new Error(assistantError?.message ?? "Could not record the assistant's reply.");
    }

    return ok({
      userMessage: toChatMessageRecord(userRow),
      assistantMessage: toChatMessageRecord(assistantRow),
      createdQuestion,
      createdContextNote,
    });
  } catch (error) {
    return err(error);
  }
}

/** Applies a discuss-proposed reframe: overwrites the question's text, records the prior text as a breadcrumb. */
export async function applyReframe(
  messageId: string,
  questionId: string,
  text: string,
): Promise<ActionResult<QuestionRecord>> {
  try {
    await assertToolAccess(TOOL_KEY);
    const supabase = await createClient();

    const { data: questionRow, error: questionReadError } = await supabase
      .from("ei_questions")
      .select("*")
      .eq("id", questionId)
      .single();
    if (questionReadError || !questionRow) throw new Error("Could not find that question.");

    const { data: updated, error: updateError } = await supabase
      .from("ei_questions")
      .update({ text, reframed_from_text: questionRow.text })
      .eq("id", questionId)
      .select("*")
      .single();
    if (updateError || !updated)
      throw new Error(updateError?.message ?? "Could not apply that reframe.");

    const { error: messageError } = await supabase
      .from("ei_chat_messages")
      .update({ applied_at: new Date().toISOString() })
      .eq("id", messageId);
    if (messageError) throw new Error(messageError.message);

    return ok({
      id: updated.id,
      inquiryId: updated.inquiry_id,
      parentId: updated.parent_id,
      depth: updated.depth,
      text: updated.text,
      status: updated.status as QuestionRecord["status"],
      hasAssumption: updated.has_assumption,
      assumptionText: updated.assumption_text,
      reframedFromText: updated.reframed_from_text,
      manualDx: updated.manual_dx,
      manualDy: updated.manual_dy,
      createdBy: updated.created_by,
      createdAt: updated.created_at,
      updatedAt: updated.updated_at,
    });
  } catch (error) {
    return err(error);
  }
}
