// Run with `node --test scripts/check-pr-text.test.mjs` (the PR workflow does).
import { test } from "node:test";
import assert from "node:assert/strict";
import { checkPrText, proseOf } from "./check-pr-text.mjs";

const GOOD_BODY =
  "## Summary\n\nAdds a check that fails a PR with a placeholder title or an empty description.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_";

test("accepts a descriptive title and body", () => {
  assert.deepEqual(
    checkPrText({
      title: "Log: weather alerts — one row per event",
      body: GOOD_BODY,
      headRef: "claude/zen-carson-fchjy1",
    }),
    [],
  );
});

test("rejects the branch-name titles that shipped", () => {
  for (const title of ["Claude/determined mayer jssl6q", "Claude/zen carson fchjy1"]) {
    const problems = checkPrText({ title, body: GOOD_BODY });
    assert.ok(problems.some((p) => /branch name/.test(p)), title);
  }
});

test("rejects a title that is the branch name with separators changed", () => {
  const problems = checkPrText({
    title: "sourcework-mobile-workspace",
    body: GOOD_BODY,
    headRef: "sourcework-mobile-workspace",
  });
  assert.ok(problems.some((p) => /branch name/.test(p)));
});

test("rejects a merge-commit title", () => {
  const problems = checkPrText({
    title: "Merge pull request #257 from wuwfdevs/sourcework-separate-source-screen",
    body: GOOD_BODY,
  });
  assert.ok(problems.some((p) => /merge commit/.test(p)));
});

test("rejects a title cut off mid-sentence", () => {
  const problems = checkPrText({
    title: "Log: alerts panel — wrap instead of truncating, and limit to WUWF's c…",
    body: GOOD_BODY,
  });
  assert.ok(problems.some((p) => /cut off/.test(p)));
});

test("rejects an empty or missing body", () => {
  for (const body of ["", "   \n", null, undefined]) {
    const problems = checkPrText({ title: "A perfectly descriptive title", body });
    assert.ok(problems.some((p) => /empty/.test(p)), String(body));
  }
});

test("a body of only commit trailers and links counts as empty", () => {
  const body =
    "Co-Authored-By: Claude <noreply@anthropic.com>\nClaude-Session: https://claude.ai/code/session_x\n\nhttps://claude.ai/code/session_x\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_x)_";
  assert.equal(proseOf(body), "");
  assert.ok(checkPrText({ title: "A perfectly descriptive title", body }).some((p) => /empty/.test(p)));
});

test("a too-short body is reported with its length", () => {
  const problems = checkPrText({ title: "A perfectly descriptive title", body: "Fixes it." });
  assert.ok(problems.some((p) => /only 9 characters/.test(p)));
});

test("headings with nothing under them are not content", () => {
  const body = "## Summary\n\n## What changed\n\n## Test plan\n";
  assert.equal(proseOf(body), "");
});

test("a very short title is rejected", () => {
  assert.ok(checkPrText({ title: "Fix", body: GOOD_BODY }).some((p) => /too short/.test(p)));
});
